/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electronicshop;

import com.sun.glass.events.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PLANDI
 */
public class SellProducts extends javax.swing.JFrame {
    
    ElectronicShop eShop ;

    /**
     * Creates new form SellProducts
     */
    public SellProducts() {
        initComponents();
        eShop = new ElectronicShop("root", "root", "electronic_shop");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        barcodeLab2 = new javax.swing.JLabel();
        productLab2 = new javax.swing.JLabel();
        descriptionLab2 = new javax.swing.JLabel();
        qantityLab2 = new javax.swing.JLabel();
        priceLab2 = new javax.swing.JLabel();
        barcodeTF2 = new javax.swing.JTextField();
        productTF2 = new javax.swing.JTextField();
        descriptionTF2 = new javax.swing.JTextField();
        quantityTF2 = new javax.swing.JTextField();
        priceTF2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        sellTable = new javax.swing.JTable();
        totDueLab = new javax.swing.JLabel();
        totDueTF = new javax.swing.JTextField();
        addItem = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        payLab = new javax.swing.JLabel();
        payTF = new javax.swing.JTextField();
        balLab = new javax.swing.JLabel();
        balTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        title.setText("     Sell Products");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        barcodeLab2.setText("Barcode");

        productLab2.setText("Product");

        descriptionLab2.setText("Description");

        qantityLab2.setText("Quantity");

        priceLab2.setText("Price(R)");

        barcodeTF2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barcodeTF2KeyPressed(evt);
            }
        });

        productTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productTF2ActionPerformed(evt);
            }
        });
        productTF2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productTF2KeyPressed(evt);
            }
        });

        sellTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Product", "Description", "Quantity", "Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(sellTable);
        if (sellTable.getColumnModel().getColumnCount() > 0) {
            sellTable.getColumnModel().getColumn(0).setPreferredWidth(25);
            sellTable.getColumnModel().getColumn(1).setPreferredWidth(50);
            sellTable.getColumnModel().getColumn(2).setPreferredWidth(50);
            sellTable.getColumnModel().getColumn(3).setPreferredWidth(10);
            sellTable.getColumnModel().getColumn(4).setPreferredWidth(15);
            sellTable.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        totDueLab.setText("Total Due");

        totDueTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totDueTFActionPerformed(evt);
            }
        });

        addItem.setText("Add Item");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });

        confirm.setText("Confirm Purchase");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        payLab.setText("Payment");

        balLab.setText("Balance");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barcodeLab2)
                            .addComponent(barcodeTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productLab2)
                            .addComponent(productTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(descriptionTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(descriptionLab2)
                                .addGap(45, 45, 45)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qantityLab2)
                            .addComponent(quantityTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(priceTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addItem))
                            .addComponent(priceLab2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totDueTF)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totDueLab)
                                    .addComponent(payLab)
                                    .addComponent(balLab))
                                .addGap(0, 34, Short.MAX_VALUE))
                            .addComponent(payTF)
                            .addComponent(balTF))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(confirm)
                .addGap(58, 58, 58)
                .addComponent(clear)
                .addGap(54, 54, 54)
                .addComponent(back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcodeLab2)
                    .addComponent(productLab2)
                    .addComponent(descriptionLab2)
                    .addComponent(qantityLab2)
                    .addComponent(priceLab2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcodeTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItem))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totDueLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totDueTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(payLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(payTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm)
                    .addComponent(clear)
                    .addComponent(back))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barcodeTF2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcodeTF2KeyPressed
    
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            
            String query = "select * from stock where barcode = ?";
            eShop.readDatabase(barcodeTF2.getText().trim(),query,getBarcodeTF2(),getProductTF2(),getDescriptionTF2(),getQuantityTF2(),getPriceTF2());
            
        }
        else if(evt.getKeyCode()== KeyEvent.VK_BACKSPACE){
            
            productTF2.setText("");
            descriptionTF2.setText("");
            priceTF2.setText("");
            quantityTF2.setText("");
            
        }
    }//GEN-LAST:event_barcodeTF2KeyPressed

    private void productTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productTF2ActionPerformed
        
                
    }//GEN-LAST:event_productTF2ActionPerformed

    private void productTF2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productTF2KeyPressed
        
         if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            
            String query = "select * from stock where product = ?";
            eShop.readDatabase(productTF2.getText().trim(),query,getBarcodeTF2(),getProductTF2(),getDescriptionTF2(),getQuantityTF2(),getPriceTF2());
            
        }
        else if(evt.getKeyCode()== KeyEvent.VK_BACKSPACE){
            
            barcodeTF2.setText("");
            descriptionTF2.setText("");
            priceTF2.setText("");
            quantityTF2.setText("");
            
        }
        
    }//GEN-LAST:event_productTF2KeyPressed

    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        
        String barcode = barcodeTF2.getText();
        String product = productTF2.getText();
        String description = descriptionTF2.getText();
        String quantity = quantityTF2.getText();
        String price = priceTF2.getText();
        
         ValidateInput val = new ValidateInput();
        
        if(!val.valBarcode(barcode)){
            
            JOptionPane.showMessageDialog(null, "Invalid barcode entry");
        }
        
        else if(!val.valProduct(product)){
            
            JOptionPane.showMessageDialog(null, "Invalid product entry");
        }
        
        else if(!val.valDescription(description)){
            
            JOptionPane.showMessageDialog(null, "Invalid description input");
        }
        
        else if(!val.valQuantity(quantity)){
            
            JOptionPane.showMessageDialog(null, "Invalid quantity entry");
        }
        
        else if(!val.valPrice(price)){
            
            JOptionPane.showMessageDialog(null, "Invalid price entry");
        }
        else{
            
            fillSellTable();
            barcodeTF2.setText("");
            productTF2.setText("");
            descriptionTF2.setText("");
            priceTF2.setText("");
            quantityTF2.setText("");
            barcodeTF2.requestFocus();
        }
        
        
    }//GEN-LAST:event_addItemActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
        Menu menu = new Menu();
        this.setVisible(false);
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        
    }//GEN-LAST:event_backActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        ValidateInput val = new ValidateInput();
        if(!val.valPayment(payTF.getText())){
           
            JOptionPane.showMessageDialog(null, "Invalid payment entry");
        }
        else{
            
            double payment = Double.parseDouble(payTF.getText());
            double balance = payment - totDue;
            balTF.setText(""+balance);
            eShop.deduct(getSellTable());
            
        }
        
        
    }//GEN-LAST:event_confirmActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel)sellTable.getModel();
        model.setRowCount(0);
        barcodeTF2.setText("");
        productTF2.setText("");
        descriptionTF2.setText("");
        priceTF2.setText("");
        quantityTF2.setText("");
        barcodeTF2.requestFocus();
        totDueTF.setText("");
        payTF.setText("");
        balTF.setText("");
        totDue = 0;
        
    }//GEN-LAST:event_clearActionPerformed

    private void totDueTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totDueTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totDueTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItem;
    private javax.swing.JButton back;
    private javax.swing.JLabel balLab;
    private javax.swing.JTextField balTF;
    private javax.swing.JLabel barcodeLab2;
    private javax.swing.JTextField barcodeTF2;
    private javax.swing.JButton clear;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel descriptionLab2;
    private javax.swing.JTextField descriptionTF2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel payLab;
    private javax.swing.JTextField payTF;
    private javax.swing.JLabel priceLab2;
    private javax.swing.JTextField priceTF2;
    private javax.swing.JLabel productLab2;
    private javax.swing.JTextField productTF2;
    private javax.swing.JLabel qantityLab2;
    private javax.swing.JTextField quantityTF2;
    private javax.swing.JTable sellTable;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totDueLab;
    private javax.swing.JTextField totDueTF;
    // End of variables declaration//GEN-END:variables

  
    
    
    
    double totDue;
    
    public void fillSellTable (){
        
        double price = Double.parseDouble(priceTF2.getText());
        int qty = Integer.parseInt(quantityTF2.getText());
        double total = price*qty;
        
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel)sellTable.getModel();
        Object [] elements = new Object[6];
        elements [0]= barcodeTF2.getText();
        elements [1]= productTF2.getText();
        elements [2]= descriptionTF2.getText();
        elements [3]= quantityTF2.getText();
        elements [4]= priceTF2.getText();
        elements [5]= total;
        model.addRow(elements);
        totDue = 0 ;
        for(int i=0; i<sellTable.getRowCount(); i++){
            
            totDue += Double.parseDouble(sellTable.getValueAt(i, 5).toString());
            
        }
        
        totDueTF.setText(""+totDue);
    }

    public JTable getSellTable() {
        return sellTable;
    }

    public JTextField getBarcodeTF2() {
        return barcodeTF2;
    }

    public JTextField getDescriptionTF2() {
        return descriptionTF2;
    }

    public JTextField getPriceTF2() {
        return priceTF2;
    }

    public JTextField getProductTF2() {
        return productTF2;
    }

    public JTextField getQuantityTF2() {
        return quantityTF2;
    }
    
    
    
    




}
